# ─── ToopSet Makefile ─────────────────────────────────────────────────────────
# Developer command interface — thin wrappers around project tools.
# See README.md for the full guide.

SHELL := /bin/bash

COMPOSE_FILE    := compose.yml
COMPOSE_PROJECT := toopset
BACKEND_DIR     := backend
FRONTEND_DIR    := frontend
UVICORN_PORT    ?= 8000
NEXT_PORT       ?= 3000
CUR_VERSION     := $(shell cat VERSION 2>/dev/null || echo "0.0.0")

.DEFAULT_GOAL := help

.PHONY: help \
        install install-backend install-frontend install-lefthook \
        dev-backend dev-frontend \
        build start \
        lint lint-backend lint-frontend \
        format format-backend format-frontend \
        typecheck typecheck-backend typecheck-frontend \
        test test-backend test-frontend test-db check \
        db-start db-stop db-status db-migrate db-check db-autogenerate \
        db-downgrade db-history db-current db-merge db-reset db-seed \
        up down logs ps \
        version version-check version-sync version-bump version-tag \
        clean clean-backend clean-frontend clean-db \
        doctor precommit prepush

## Install
install: install-backend install-frontend install-lefthook ## Install all dependencies

install-backend: ## Install backend Python dependencies
	@cd $(BACKEND_DIR) && pip3 install -r requirements.txt

install-frontend: ## Install frontend dependencies (pnpm)
	@cd $(FRONTEND_DIR) && pnpm install

install-lefthook: ## Register git hooks (lefthook)
	@cd $(FRONTEND_DIR) && pnpm exec lefthook install

## Development
dev-backend: ## Start backend with auto-reload on :$(UVICORN_PORT)
	@cd $(BACKEND_DIR) && uvicorn app.main:app --host 0.0.0.0 --port $(UVICORN_PORT) --reload

dev-frontend: ## Start frontend (Turbopack HMR) on :$(NEXT_PORT)
	@cd $(FRONTEND_DIR) && pnpm dev

## Build
build: ## Build frontend for production
	@cd $(FRONTEND_DIR) && pnpm build

start: ## Start production Next.js server on :$(NEXT_PORT)
	@cd $(FRONTEND_DIR) && exec pnpm start

## Quality
lint: lint-backend lint-frontend ## Lint all (check-only — never modifies source)

lint-backend: ## Lint backend (Ruff)
	@cd $(BACKEND_DIR) && ruff check .

lint-frontend: ## Lint frontend (ESLint)
	@cd $(FRONTEND_DIR) && pnpm lint

format: format-backend format-frontend ## Format all code

format-backend: ## Format backend (Ruff)
	@cd $(BACKEND_DIR) && ruff format .

format-frontend: ## Format frontend (Prettier)
	@cd $(FRONTEND_DIR) && pnpm format

typecheck: typecheck-backend typecheck-frontend ## Type-check all

typecheck-backend: ## Type-check backend (mypy)
	@cd $(BACKEND_DIR) && mypy app

typecheck-frontend: ## Type-check frontend (tsc)
	@cd $(FRONTEND_DIR) && pnpm typecheck

## Testing
test: test-backend test-frontend ## Run all tests

test-db: ## Create toopset_test database (no-op if it exists)
	@PGPASSWORD=$${POSTGRES_PASSWORD:-toopset_secret} psql -h $${POSTGRES_HOST:-localhost} -p $${POSTGRES_PORT:-5432} -U $${POSTGRES_USER:-toopset} -d postgres -c "CREATE DATABASE toopset_test" 2>/dev/null || true

test-backend: test-db ## Run backend tests (pytest)
	@cd $(BACKEND_DIR) && python3 -m pytest tests/ -v --tb=short -W ignore::DeprecationWarning

test-frontend: ## Run frontend tests (Vitest)
	@cd $(FRONTEND_DIR) && pnpm test

check: lint typecheck build ## Lint + typecheck + build (pre-commit gate)

## Database
db-start: ## Start Postgres + Redis (Docker)
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) up -d postgres redis

db-stop: ## Stop Postgres + Redis
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) stop postgres redis

db-status: ## Show DB container status
	@for svc in postgres redis; do \
		status=$$(docker inspect --format='{{.State.Status}}' $(COMPOSE_PROJECT)-$$svc 2>/dev/null || echo "not found"); \
		[ "$$status" = "running" ] && echo "  $$svc: running" || echo "  $$svc: $$status"; \
	done

db-migrate: ## Apply Alembic migrations
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations upgrade

db-check: ## Static migration check (+ alembic check if DB is up)
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations check

db-autogenerate: ## Create autogenerated migration: make db-autogenerate MSG="desc"
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations autogenerate "$(MSG)"

db-downgrade: ## Roll back: make db-downgrade REV=-1
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations downgrade "$(REV)"

db-history: ## Show migration history
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations history

db-current: ## Show current migration revision
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations current

db-merge: ## Merge migration heads: make db-merge MSG="msg"
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations merge "$(MSG)"

db-reset: ## Wipe and recreate DB volumes (asks confirmation)
	@echo "WARNING: this deletes all database data!"; \
	read -p "  Continue? [y/N] " ans; \
	if [ "$$ans" = "y" ] || [ "$$ans" = "Y" ]; then \
		docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) down -v postgres redis && \
		docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) up -d postgres redis; \
	else echo "  Cancelled"; fi

db-seed: ## Seed database with test data
	@cd $(BACKEND_DIR) && python3 scripts/generate-placeholder-court-images.py -q 2>/dev/null; python3 -m scripts.seed

## Docker
up: ## Start all Docker services (postgres + redis)
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) up -d --wait

down: ## Stop all Docker services
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) down

logs: ## Tail logs from all services
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) logs -f

ps: ## Show status of Docker services
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) ps

## Version
version: ## Show current version
	@echo $(CUR_VERSION)

version-check: ## Verify version consistency across all files
	@python3 scripts/check_version.py --all

version-sync: ## Sync VERSION into backend __init__ + frontend package.json
	@python3 scripts/version.py sync

version-bump: ## Bump version: make version-bump BUMP=patch|minor|major
	@test -n "$(BUMP)" || { echo "  Usage: make version-bump BUMP=patch|minor|major"; exit 1; }
	@python3 scripts/version.py bump $(BUMP)

version-tag: ## Tag current version (v$(CUR_VERSION)) and push
	@git tag -a "v$(CUR_VERSION)" -m "Release v$(CUR_VERSION)" && git push origin "v$(CUR_VERSION)"

## Maintenance
clean: clean-backend clean-frontend ## Remove build and cache artifacts

clean-backend: ## Remove backend caches
	@find $(BACKEND_DIR) -type d \( -name '__pycache__' -o -name '*.egg-info' \
		-o -name '.pytest_cache' -o -name '.ruff_cache' -o -name '.mypy_cache' \) \
		-prune -exec rm -rf {} +
	@find $(BACKEND_DIR) -type f -name '*.pyc' -delete
	@rm -f $(BACKEND_DIR)/.coverage

clean-frontend: ## Remove frontend build artifacts
	@rm -rf $(FRONTEND_DIR)/.next $(FRONTEND_DIR)/dist

clean-db: ## Delete all Docker volumes (asks confirmation)
	@echo "WARNING: this deletes all data!"; \
	read -p "  Type 'yes' to confirm: " ans; \
	if [ "$$ans" = "yes" ]; then \
		docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) down -v; \
	else echo "  Cancelled"; fi

doctor: ## Check system prerequisites
	@for c in docker python3 node pnpm; do \
		command -v $$c >/dev/null 2>&1 && echo "  ✓ $$c" || echo "  ✗ $$c (missing)"; \
	done
	@command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1 \
		&& echo "  ✓ Docker daemon" || echo "  ✗ Docker daemon not running"
	@for p in 5432 6379; do \
		lsof -i :$$p >/dev/null 2>&1 && echo "  ✓ port $$p in use" \
			|| echo "  ⚠ port $$p free — run 'make db-start'"; \
	done
	@python3 -c "import fastapi" >/dev/null 2>&1 \
		&& echo "  ✓ Python deps" || echo "  ⚠ Python deps missing — run 'make install-backend'"
	@[ -d $(FRONTEND_DIR)/node_modules ] \
		&& echo "  ✓ Node deps" || echo "  ⚠ Node deps missing — run 'make install-frontend'"

## Git Hooks
precommit: ## Run lefthook pre-commit hook
	@cd $(FRONTEND_DIR) && pnpm exec lefthook run pre-commit

prepush: ## Run lefthook pre-push hook
	@cd $(FRONTEND_DIR) && pnpm exec lefthook run pre-push

## Help
help: ## Show this help
	@awk 'BEGIN { FS = ":.*?## "; print "" } \
		/^## / { print "\n" substr($$0, 4); next } \
		/^[A-Za-z0-9_.-]+:.*?## / { printf "  %-26s %s\n", $$1, $$2 }' $(MAKEFILE_LIST)
