# ─── TOOPSET / MAKEFILE ───────────────────────────────────
# Developer command interface — thin wrappers around project tools.
# See README.md for the full guide.

SHELL := /bin/bash

# ─── CONFIG ───────────────────────────────────────────────
ESC    := $(shell printf '\033')
BOLD   := $(ESC)[1m
RESET  := $(ESC)[0m
GREEN  := $(ESC)[32m
YELLOW := $(ESC)[33m
RED    := $(ESC)[31m
GREY   := $(ESC)[90m

COMPOSE_FILE    := compose.yml
COMPOSE_PROJECT := toopset
PROJECT_NAME    := ToopSet
BACKEND_DIR     := backend
FRONTEND_DIR    := frontend
UVICORN_PORT    ?= 8000

.DEFAULT_GOAL := help

.PHONY: help \
	install \
	dev-backend dev-frontend build \
	lint format typecheck test check \
	db-start db-stop db-migrate db-check db-autogenerate \
	db-downgrade db-reset db-seed \
	clean doctor

# ─── INSTALL ──────────────────────────────────────────────
install: ## Install all dependencies
	@cd $(BACKEND_DIR) && pip3 install -r requirements.txt
	@cd $(FRONTEND_DIR) && pnpm install && pnpm exec lefthook install
	@echo "  $(GREEN)✓$(RESET) Dependencies installed"

# ─── DEV / BUILD ──────────────────────────────────────────
dev-backend: ## Backend API + reload
	@cd $(BACKEND_DIR) && LOG_FORMAT=console uvicorn app.main:app --host 0.0.0.0 --port $(UVICORN_PORT) --reload

dev-frontend: ## Frontend + HMR
	@cd $(FRONTEND_DIR) && pnpm dev

build: ## Production frontend build
	@cd $(FRONTEND_DIR) && pnpm build
	@echo "  $(GREEN)✓$(RESET) Frontend built"

# ─── QUALITY / TEST ───────────────────────────────────────
lint: ## Lint backend + frontend
	@cd $(BACKEND_DIR) && ruff check .
	@cd $(FRONTEND_DIR) && pnpm lint
	@echo "  $(GREEN)✓$(RESET) Linted"

format: ## Format backend + frontend
	@cd $(BACKEND_DIR) && ruff format .
	@cd $(FRONTEND_DIR) && pnpm format
	@echo "  $(GREEN)✓$(RESET) Formatted"

typecheck: ## Typecheck backend + frontend
	@cd $(BACKEND_DIR) && mypy app
	@cd $(FRONTEND_DIR) && pnpm typecheck
	@echo "  $(GREEN)✓$(RESET) Type check passed"

test: ## Test backend + frontend
	@cd $(BACKEND_DIR) && TEST_DATABASE_URL=$${TEST_DATABASE_URL:-postgresql+asyncpg://toopset:toopset_secret@localhost:5432/toopset_test} python3 -m pytest tests/ -v --tb=short -W ignore::DeprecationWarning
	@cd $(FRONTEND_DIR) && pnpm test

check: lint typecheck build ## Lint + typecheck + build
	@echo "  $(GREEN)✓$(RESET) All checks passed"

# ─── DB ───────────────────────────────────────────────────
db-start: ## Start Postgres + Redis
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) up -d postgres redis
	@echo "  $(GREEN)✓$(RESET) Postgres and Redis started"

db-stop: ## Stop Postgres + Redis
	@docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) stop postgres redis
	@echo "  $(GREEN)✓$(RESET) Postgres and Redis stopped"

db-migrate: ## Apply DB migrations
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations upgrade
	@echo "  $(GREEN)✓$(RESET) Alembic migrations applied"

db-check: ## Check migration drift
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations check
	@echo "  $(GREEN)✓$(RESET) Migration check passed"

db-autogenerate: ## New migration (MSG=..)
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations autogenerate "$(MSG)"
	@echo "  $(GREEN)✓$(RESET) Autogenerated migration created"

db-downgrade: ## Rollback (REV=..)
	@cd $(BACKEND_DIR) && python3 -m scripts.run_migrations downgrade "$(REV)"
	@echo "  $(GREEN)✓$(RESET) Rollback applied"

db-reset: ## Reset DB volumes (wipe!)
	@echo "  $(YELLOW)WARNING$(RESET) this deletes all database data!"; \
	read -p "  Continue? [y/N] " ans; \
	if [ "$$ans" = "y" ] || [ "$$ans" = "Y" ]; then \
		docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) down -v postgres redis && \
		docker compose -f $(COMPOSE_FILE) -p $(COMPOSE_PROJECT) up -d postgres redis && \
		echo "  $(GREEN)✓$(RESET) Databases recreated"; \
	else \
		echo "  $(GREY)Operation cancelled$(RESET)"; \
	fi

db-seed: ## Seed test data
	@cd $(BACKEND_DIR) && python3 -m scripts.seed
	@echo "  $(GREEN)✓$(RESET) Database seeded"

# ─── SYSTEM ───────────────────────────────────────────────
clean: ## Remove caches + builds
	@find $(BACKEND_DIR) -type d \( -name '__pycache__' -o -name '*.egg-info' \
		-o -name '.pytest_cache' -o -name '.ruff_cache' -o -name '.mypy_cache' \) \
		-prune -exec rm -rf {} +
	@find $(BACKEND_DIR) -type f -name '*.pyc' -delete
	@rm -f $(BACKEND_DIR)/.coverage
	@rm -rf $(FRONTEND_DIR)/.next $(FRONTEND_DIR)/dist
	@echo "  $(GREEN)✓$(RESET) Cleaned"

doctor: ## Check prerequisites
	@printf "\n$(BOLD)System Check - $(PROJECT_NAME)$(RESET)\n"
	@printf -- "$(GREY)----------------------------$(RESET)\n"
	@for c in docker python3 node pnpm; do \
		command -v $$c >/dev/null 2>&1 && echo "  $(GREEN)✓$(RESET) $$c" || echo "  $(RED)✗$(RESET) $$c (missing)"; \
	done
	@command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1 \
		&& echo "  $(GREEN)✓$(RESET) Docker daemon" || echo "  $(RED)✗$(RESET) Docker daemon not running"
	@for p in 5432 6379; do \
		lsof -i :$$p >/dev/null 2>&1 && echo "  $(GREEN)✓$(RESET) port $$p in use" \
			|| echo "  $(YELLOW)⚠$(RESET) port $$p free — run 'make db-start'"; \
	done
	@python3 -c "import fastapi" >/dev/null 2>&1 \
		&& echo "  $(GREEN)✓$(RESET) Python deps" || echo "  $(YELLOW)⚠$(RESET) Python deps missing — run 'make install'"
	@[ -d $(FRONTEND_DIR)/node_modules ] \
		&& echo "  $(GREEN)✓$(RESET) Node deps" || echo "  $(YELLOW)⚠$(RESET) Node deps missing — run 'make install'"
	@printf -- "$(GREY)----------------------------$(RESET)\n\n"

# ─── HELP ─────────────────────────────────────────────────
help: ## Show this help
	@printf "\n"
	@printf "\033[1;36m"
	@printf '%s\n' \
		' ████████╗ ██████╗  ██████╗  ██████╗  ██████╗  ██████╗  ████████╗' \
		' ╚══██╔══╝ ██╔══██╗ ██╔══██╗ ██╔══██╗ ██╔════╝ ██╔════╝ ╚══██╔══╝' \
		'    ██║    ██║  ██║ ██║  ██║ ██████╔╝ ╚█████╗  █████╗      ██║' \
		'    ██║    ██║  ██║ ██║  ██║ ██╔═══╝   ╚═══██╗ ██╔══╝      ██║' \
		'    ╚═╝    ╚█████╔╝ ╚█████╔╝ ██║      ██████╔╝ ███████╗    ╚═╝'
	@printf "\033[0m\n"
	@printf "\n"
	@awk 'BEGIN {FS = ":.*##"; section = ""; last = ""; line = "──────────────────────────────────────────────────────────────────────"} \
	/^# ─── / { \
		s=$$0; gsub(/^# ──+ /,"",s); gsub(/ ──+.*$$/,"",s); section=s; \
	} \
	/^[a-zA-Z_-]+:.*##/ { \
		t=$$1; d=$$2; \
		if (section != last) { \
			if (last != "") printf "\033[2;37m└" line "┘\033[0m\n\n"; \
			printf "\033[2;37m┌──────────────────────────────────────────────────────────────────────┐\033[0m\n"; \
			printf "\033[2;37m│ \033[1;37m%-60s\033[0m \033[2;37m        │\033[0m\n", section; \
			printf "\033[2;37m├──────────────────────────────────────────────────────────────────────┤\033[0m\n"; \
			last = section; \
		} \
		printf "\033[2;37m│ \033[1;36m%-28s\033[0m \033[2;37m%-39s\033[0m \033[2;37m│\033[0m\n", t, d; \
	} END {printf "\033[2;37m└" line "┘\033[0m\n\n";}' Makefile
	@printf "\033[2;37m────────────────────────────────────────────────────────────────────────\033[0m\n"
	@printf "\033[2;37m→\033[0m \033[1;37mmake\033[0m \033[1;36m<command>\033[0m\n"
	@printf "\n"
