#!/usr/bin/env python3
"""
Alembic migration runner — wraps alembic commands with richer error output.

Usage from Makefile or CI:

  python3 -m scripts.run_migrations check    # Static revision check + alembic check
  python3 -m scripts.run_migrations upgrade  # alembic upgrade head
  python3 -m scripts.run_migrations downgrade  # alembic downgrade -1  (or +N / base)
  python3 -m scripts.run_migrations history  # alembic history
  python3 -m scripts.run_migrations current  # alembic current
  python3 -m scripts.run_migrations autogenerate "msg"  # alembic revision --autogenerate -m
  python3 -m scripts.run_migrations merge "msg"  # alembic merge heads -m

Exit 0 on success, non-zero on failure with a clear error message.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def _alembic(*args: str) -> int:
    """Run alembic in backend/ directory and return exit code."""
    backend = Path(__file__).resolve().parent.parent
    result = subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=backend,
        capture_output=False,
    )
    return result.returncode


def _check_revisions_static() -> int:
    """Run the static check_revisions script as a subprocess."""
    backend = Path(__file__).resolve().parent.parent
    result = subprocess.run(
        [sys.executable, "-m", "scripts.check_revisions", "--strict"],
        cwd=backend,
        capture_output=False,
    )
    return result.returncode


def cmd_check() -> int:
    """Static check + alembic check (requires DB)."""
    rc = _check_revisions_static()

    # alembic check (requires DB connection) — non-fatal if DB unavailable
    print("\n  ── Alembic head vs DB check ──")
    r = _alembic("check")
    if r != 0:
        print("  alembic check failed (is the DB running?)")
        print("  Static check passed; this is a DB-level issue.")
        rc = rc or 1
    return rc


def cmd_upgrade() -> int:
    """Run all pending migrations."""
    print("  Running migrations...")
    return _alembic("upgrade", "head")


def cmd_downgrade() -> int:
    """Roll back one revision.  Accept +N or base as arg."""
    rev = sys.argv[2] if len(sys.argv) > 2 else "-1"
    print(f"  Rolling back to: {rev}")
    return _alembic("downgrade", rev)


def cmd_history() -> int:
    """Show migration history."""
    return _alembic("history")


def cmd_current() -> int:
    """Show current revision."""
    return _alembic("current")


def cmd_autogenerate() -> int:
    """Create a new autogenerated migration."""
    if len(sys.argv) < 3:
        print("  Usage: python3 -m scripts.run_migrations autogenerate <message>", file=sys.stderr)
        return 1
    message = " ".join(sys.argv[2:])
    print(f"  Creating autogenerated revision: {message}")
    return _alembic("revision", "--autogenerate", "-m", message)


def cmd_merge() -> int:
    """Merge migration heads."""
    if len(sys.argv) < 3:
        print("  Usage: python3 -m scripts.run_migrations merge <message>", file=sys.stderr)
        return 1
    message = " ".join(sys.argv[2:])
    print(f"  Merging heads: {message}")
    return _alembic("merge", "heads", "-m", message)


COMMANDS = {
    "check": cmd_check,
    "upgrade": cmd_upgrade,
    "downgrade": cmd_downgrade,
    "history": cmd_history,
    "current": cmd_current,
    "autogenerate": cmd_autogenerate,
    "merge": cmd_merge,
}


def main() -> int:
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        print("  Usage: python3 -m scripts.run_migrations <command> [args]", file=sys.stderr)
        print(f"  Commands: {', '.join(sorted(COMMANDS))}", file=sys.stderr)
        return 1

    return COMMANDS[sys.argv[1]]()


if __name__ == "__main__":
    sys.exit(main())
