declare module "lucide-react" {
  import type { FC, SVGProps } from "react"

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number
    absoluteStrokeWidth?: boolean
  }

  export type Icon = FC<LucideProps>

  export const AlertTriangle: Icon
  export const RefreshCw: Icon
  export const AlertCircle: Icon
  export const X: Icon
  export const Loader2: Icon
  export const Frown: Icon
  export const CheckCircle2: Icon
  export const Ban: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Trash2: Icon
  export const Pencil: Icon
  export const Plus: Icon
  export const Search: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronDown: Icon
  export const ChevronUp: Icon
  export const ChevronsUpDown: Icon
  export const Menu: Icon
  export const Bell: Icon
  export const BellDot: Icon
  export const User: Icon
  export const UserCircle: Icon
  export const LogOut: Icon
  export const Settings: Icon
  export const Home: Icon
  export const Calendar: Icon
  export const Clock: Icon
  export const MapPin: Icon
  export const Star: Icon
  export const Phone: Icon
  export const Mail: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const Users: Icon
  export const Building: Icon
  export const Building2: Icon
  export const Image: Icon
  export const ImagePlus: Icon
  export const Upload: Icon
  export const Download: Icon
  export const Filter: Icon
  export const SlidersHorizontal: Icon
  export const SortAsc: Icon
  export const SortDesc: Icon
  export const MoreHorizontal: Icon
  export const MoreVertical: Icon
  export const Copy: Icon
  export const Check: Icon
  export const ChevronFirst: Icon
  export const ChevronLast: Icon
  export const ChevronsLeft: Icon
  export const ChevronsRight: Icon
  export const PanelLeft: Icon
  export const PanelRight: Icon
  export const Sun: Icon
  export const Moon: Icon
  export const Laptop: Icon
  export const Wallet: Icon
  export const CreditCard: Icon
  export const Receipt: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const ArrowUp: Icon
  export const ArrowDown: Icon
  export const ArrowDownLeft: Icon
  export const ArrowUpRight: Icon
  export const ExternalLink: Icon
  export const Share2: Icon
  export const Heart: Icon
  export const MessageCircle: Icon
  export const MessageSquare: Icon
  export const ThumbsUp: Icon
  export const ThumbsDown: Icon
  export const Flag: Icon
  export const Info: Icon
  export const HelpCircle: Icon
  export const FileText: Icon
  export const BarChart3: Icon
  export const TrendingUp: Icon
  export const DollarSign: Icon
  export const Percent: Icon
  export const Layers: Icon
  export const Grid: Icon
  export const List: Icon
  export const Map: Icon
  export const Navigation: Icon
  export const Camera: Icon
  export const Video: Icon
  export const Send: Icon
  export const Reply: Icon
  export const Repeat: Icon
  export const Undo2: Icon
  export const Redo2: Icon
  export const Maximize2: Icon
  export const Minimize2: Icon
  export const Lock: Icon
  export const Unlock: Icon
  export const Key: Icon
  export const Gift: Icon
  export const Award: Icon
  export const Medal: Icon
  export const Trophy: Icon
  export const Activity: Icon
  export const Zap: Icon
  export const Target: Icon
  export const Crosshair: Icon
  export const Compass: Icon
  export const Globe: Icon
  export const BookOpen: Icon
  export const Newspaper: Icon
  export const Printer: Icon
  export const Inbox: Icon
  export const Archive: Icon
  export const Delete: Icon
  export const ClipboardList: Icon
  export const ClipboardCheck: Icon
  export const ClipboardX: Icon
  export const GripVertical: Icon
  export const GripHorizontal: Icon
  export const AlignRight: Icon
  export const AlignLeft: Icon
  export const AlignCenter: Icon
  export const Bold: Icon
  export const Italic: Icon
  export const Underline: Icon
  export const Link: Icon
  export const Link2: Icon
  export const Unlink: Icon
  export const Hash: Icon
  export const AtSign: Icon
  export const Circle: Icon
  export const CircleDot: Icon
  export const CircleOff: Icon
  export const Square: Icon
  export const Triangle: Icon
  export const Diamond: Icon
  export const Hexagon: Icon
  export const Octagon: Icon
  export const BadgeCheck: Icon
  export const BadgeX: Icon
  export const BadgeAlert: Icon
  export const BadgeInfo: Icon
  export const Sparkles: Icon
  export const Wand2: Icon
  export const WandSparkles: Icon
  export const Palette: Icon
  export const Music: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const Mic: Icon
  export const MicOff: Icon
  export const Headphones: Icon
  export const Radio: Icon
  export const Tv: Icon
  export const Monitor: Icon
  export const Tablet: Icon
  export const Smartphone: Icon
  export const Watch: Icon
  export const BatteryCharging: Icon
  export const BatteryFull: Icon
  export const BatteryLow: Icon
  export const BatteryMedium: Icon
  export const Wifi: Icon
  export const WifiOff: Icon
  export const Signal: Icon
  export const Bluetooth: Icon
  export const BluetoothConnected: Icon
  export const BluetoothOff: Icon
  export const Cloud: Icon
  export const CloudOff: Icon
  export const CloudRain: Icon
  export const CloudSnow: Icon
  export const CloudLightning: Icon
  export const CloudDrizzle: Icon
  export const CloudFog: Icon
  export const SunMedium: Icon
  export const SunSnow: Icon
  export const Sunrise: Icon
  export const Sunset: Icon
  export const Thermometer: Icon
  export const Umbrella: Icon
  export const Wind: Icon
  export const RotateCw: Icon
  export const RotateCcw: Icon
  export const RefreshCcw: Icon
  export const Move: Icon
  export const MoveHorizontal: Icon
  export const MoveVertical: Icon
  export const Expand: Icon
  export const Collapse: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon
  export const Minus: Icon
  export const Equal: Icon
  export const Slash: Icon
  export const PercentIcon: Icon
  export const ShieldX: Icon
  export const LayoutDashboard: Icon
  export const XCircle: Icon
  export const CalendarCheck: Icon
  export const ListChecks: Icon
  export const Timer: Icon
  export const CheckCircle: Icon
  export const ShieldAlert: Icon
  export const History: Icon
  export const Settings2: Icon
  export const Save: Icon
  export const Tag: Icon
  export const Type: Icon
  export const ToggleRight: Icon
  export const CalendarPlus: Icon
  export const CalendarDays: Icon
  export const CheckCheck: Icon
  export const Gavel: Icon
  export const UserCog: Icon
  export type LucideIcon = Icon
  export const Play: Icon
  export const Goal: Icon
  export const Hand: Icon
  export const Calculator: Icon
  export const Store: Icon
  export const Bath: Icon
  export const GlassWater: Icon
  export const LayoutGrid: Icon
  export const ArmchairIcon: Icon
  export const Fan: Icon
  export const Car: Icon
  export const DoorOpen: Icon
  export const Volleyball: Icon
  export const Swords: Icon
  export const Footprints: Icon
  export const MessageSquareText: Icon
}
