"""make_email_nullable_phone_required

Revision ID: 44f33e171792
Revises: 0008
Create Date: 2026-06-29 10:43:02.664712

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44f33e171792"
down_revision: Union[str, None] = "0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill any existing NULL phones before making the column NOT NULL
    op.execute("UPDATE contact_messages SET phone = 'بدون شماره' WHERE phone IS NULL")
    op.alter_column(
        "contact_messages", "email", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    op.alter_column(
        "contact_messages", "phone", existing_type=sa.VARCHAR(length=32), nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("contact_messages", "phone", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column(
        "contact_messages", "email", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    # ### end Alembic commands ###
