"""add_soft_delete_and_payment_fields

Revision ID: e0adc347178c
Revises: 0003
Create Date: 2026-05-29 15:40:52.657039

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0adc347178c"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("subject", sa.String(length=512), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "favorites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("court_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["court_id"], ["courts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "court_id", name="uq_user_court_favorite"),
    )
    op.create_index(op.f("ix_favorites_court_id"), "favorites", ["court_id"], unique=False)
    op.create_index(op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False)
    op.add_column(
        "bookings", sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("bookings", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        "bookings",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bookings",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_bookings_is_deleted"), "bookings", ["is_deleted"], unique=False)
    op.add_column(
        "courts", sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("courts", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        "courts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_courts_is_deleted"), "courts", ["is_deleted"], unique=False)
    op.alter_column(
        "logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("payments", sa.Column("gateway_name", sa.String(length=64), nullable=True))
    op.add_column("payments", sa.Column("card_number", sa.String(length=32), nullable=True))
    op.add_column("payments", sa.Column("ref_id", sa.String(length=64), nullable=True))
    op.add_column(
        "payments", sa.Column("gateway_fee", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column("payments", sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        "payments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(None, "payments", "bookings", ["booking_id"], ["id"])
    op.alter_column(
        "penalties",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "reviews", sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("reviews", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        "reviews",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_reviews_is_deleted"), "reviews", ["is_deleted"], unique=False)
    op.add_column(
        "users", sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(op.f("ix_users_is_deleted"), "users", ["is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_deleted"), table_name="users")
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("users", "deleted_at")
    op.drop_column("users", "is_deleted")
    op.drop_index(op.f("ix_reviews_is_deleted"), table_name="reviews")
    op.alter_column(
        "reviews",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("reviews", "deleted_at")
    op.drop_column("reviews", "is_deleted")
    op.alter_column(
        "penalties",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.alter_column(
        "payments",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("payments", "paid_at")
    op.drop_column("payments", "gateway_fee")
    op.drop_column("payments", "ref_id")
    op.drop_column("payments", "card_number")
    op.drop_column("payments", "gateway_name")
    op.alter_column(
        "logs",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_courts_is_deleted"), table_name="courts")
    op.alter_column(
        "courts",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("courts", "deleted_at")
    op.drop_column("courts", "is_deleted")
    op.drop_index(op.f("ix_bookings_is_deleted"), table_name="bookings")
    op.alter_column(
        "bookings",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bookings",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("bookings", "deleted_at")
    op.drop_column("bookings", "is_deleted")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_court_id"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_table("contact_messages")
    # ### end Alembic commands ###
